### ISSUE TITLE
BeaconState.ConvertToIndexed: panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by guidovranken** [protolambda/zrnt#13]
```
panic: runtime error: makeslice: cap out of range

goroutine 17 [running, locked to thread]:
github.com/protolambda/zrnt/eth2/beacon.(*BeaconState).ConvertToIndexed(0xc00029c000, 0xc002fd8b08, 0x20, 0xc000096f01, 0xc1d4fd004e1156db)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/state.go:469 +0x2c5
github.com/protolambda/zrnt/eth2/beacon/block_processing.ProcessAttestation(0xc00029c000, 0xc002fd8b08, 0xc002fd8b90, 0x524f7b)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/block_processing/block_attestation.go:58 +0x32a
github.com/protolambda/zrnt/eth2/beacon/block_processing.ProcessBlockAttestations(0xc00029c000, 0xc0000d0488, 0x0, 0x0)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/block_processing/block_attestation.go:16 +0x15b
github.com/protolambda/zrnt/eth2/beacon/transition.ProcessBlock(0xc00029c000, 0xc0000d0488, 0x0, 0x0)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/transition/block_transition.go:28 +0xc5
github.com/protolambda/zrnt/eth2/beacon/transition.StateTransition(0xc00029c000, 0xc0000d0488, 0x0, 0xc0000d61f0, 0x20)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/transition/transition.go:37 +0xb1
_/home/jhg/eth-2019/x/eth2.0-fuzzing/files/fuzzers/block/zrnt.Fuzz(0x6b97d50, 0xb7c, 0xb7c, 0x0, 0xc000000600, 0xc00021c000)
	/home/jhg/eth-2019/x/eth2.0-fuzzing/files/fuzzers/block/zrnt/fuzz.go:78 +0x8ac
main.block_LLVMFuzzerTestOneInput(0x6b97d50, 0xb7c, 0x3e481f8)
```

Because ```len(participants)``` is smaller than ```len(custodyBit1Indices)``` and it is tried to create a slice of a negative size in ```custodyBit0Indices := make([]ValidatorIndex, 0, len(participants)-len(custodyBit1Indices))```.

**Comment by protolambda** [comment]
See fea0815
