### ISSUE TITLE
v07x branch: panic: runtime error: index out of range in ValidateIndexedAttestation

### ISSUE THREAD

**Issue by guidovranken** [protolambda/zrnt#15]
```go
panic: runtime error: index out of range

goroutine 17 [running, locked to thread]:
github.com/protolambda/zrnt/eth2/beacon.(*BeaconState).ValidateIndexedAttestation(0xc0004c2000, 0xc002a27078, 0x0, 0x0)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/state.go:518 +0xb05
github.com/protolambda/zrnt/eth2/beacon/block_processing.ProcessAttesterSlashing(0xc0004c2000, 0xc002a26f20, 0x7f92f4be0200, 0x20300000000000)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/block_processing/block_attester_slashing.go:33 +0x1bc
github.com/protolambda/zrnt/eth2/beacon/block_processing.ProcessBlockAttesterSlashings(0xc0004c2000, 0xc0005fe250, 0x0, 0x0)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/block_processing/block_attester_slashing.go:15 +0x13b
github.com/protolambda/zrnt/eth2/beacon/transition.ProcessBlock(0xc0004c2000, 0xc0005fe250, 0x0, 0x0)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/transition/block_transition.go:28 +0xc3
github.com/protolambda/zrnt/eth2/beacon/transition.StateTransition(0xc0004c2000, 0xc0005fe250, 0x2100, 0x0, 0x3b9aca00)
	/home/jhg/eth-2019/eth2.0-fuzzing/tmp/go/packages/src/github.com/protolambda/zrnt/eth2/beacon/transition/transition.go:37 +0xb1
_/home/jhg/eth-2019/x/eth2.0-fuzzing/files/fuzzers/block/zrnt.Fuzz(0x6353030, 0x2167, 0x2167, 0x0, 0xc000000600, 0xc000073d00)
```

Line is

```go
if !state.ValidatorRegistry.IsValidatorIndex(bit0Indices[len(bit0Indices)-1]) {
```

(```bit0Indices``` length check is commented out)

**Comment by protolambda** [comment]
Fixed in 23e9472c5e0cd226b5664c201067444829bdca25
